// ─── ENUMS ─────────────────────────────────────────────────────────────────────

export enum ClaimType {
  EU261 = 'EU261',
  RECALL = 'RECALL',
  CLASS_ACTION = 'CLASS_ACTION',
}

export enum ClaimStatus {
  DISCOVERED = 'DISCOVERED',       // Found, not yet actioned
  EMAIL_DRAFTED = 'EMAIL_DRAFTED', // Letter generated by Claude
  SUBMITTED = 'SUBMITTED',         // Sent to airline / company
  PENDING = 'PENDING',             // Awaiting response (>14 days)
  RESOLVED = 'RESOLVED',           // Paid out
  REJECTED = 'REJECTED',           // Denied — can appeal
}

export type RemedyType = 'REFUND' | 'REPLACEMENT' | 'REPAIR' | 'STOP_USE'

export type CompensationTier = 250 | 400 | 600 // EUR, per EU261 Article 7

// ─── CLAIM PAYLOADS (JSONB in DB) ──────────────────────────────────────────────

export interface EU261Payload {
  flight_number: string
  airline_iata: string           // 2-letter IATA code
  departure_airport: string      // 3-letter IATA
  arrival_airport: string
  scheduled_date: string         // ISO date (YYYY-MM-DD)
  actual_delay_minutes: number
  compensation_tier: CompensationTier
  regulation: 'EU261' | 'UK261' // UK261 post-Brexit
}

export interface RecallPayload {
  cpsc_recall_id: string
  product_name: string
  amazon_order_id: string | null
  purchase_date: string | null   // ISO string
  remedy_type: RemedyType
  claim_url: string
}

export interface ClassActionPayload {
  settlement_id: string
  case_name: string
  deadline: string               // ISO date
  eligibility_met: string[]      // Human-readable criteria user satisfies
  claim_url: string
}

// ─── CORE ENTITIES ─────────────────────────────────────────────────────────────

export interface Claim {
  id: string
  user_id: string
  type: ClaimType
  status: ClaimStatus
  amount_est_usd: number | null
  payload: EU261Payload | RecallPayload | ClassActionPayload
  created_at: string
  updated_at: string
}

export interface RecallItem {
  id: string
  cpsc_recall_id: string
  title: string
  product_names: string[]
  brands: string[]
  category: string
  recall_date: string            // ISO date
  remedy_type: RemedyType
  hazard_description: string
  claim_url: string | null
  estimated_refund_usd: number | null
  is_active: boolean
}

export interface ClassActionItem {
  id: string
  external_id: string
  case_name: string
  description: string
  affected_products: string[]
  affected_brands: string[]
  deadline: string | null        // ISO date
  min_payout_usd: number | null
  max_payout_usd: number | null
  claim_url: string
  eligibility_rules: EligibilityRule[]
  is_active: boolean
}

export interface EligibilityRule {
  type: 'PRODUCT_OWNED' | 'DATE_RANGE' | 'US_STATE' | 'MIN_AMOUNT_SPENT'
  value: string
}

// ─── CLIENT-SIDE ONLY (never leave the browser) ────────────────────────────────

/** Full parsed Amazon order row — stays in browser memory only */
export interface AmazonOrderItem {
  order_id: string
  product_name: string
  purchase_date: Date
  price_usd: number
  asin: string | null
  category: string | null
}

// ─── SERVER-SAFE TYPES (OK to transmit) ────────────────────────────────────────

/**
 * Stripped order summary — only what's needed for recall matching server-side.
 * No ASIN (purchase fingerprint), no raw category strings.
 */
export interface OrderSummary {
  order_id: string
  product_name: string
  purchase_date: string          // ISO string
  price_usd: number
}

// ─── MATCHING ──────────────────────────────────────────────────────────────────

export interface MatchResult {
  item: AmazonOrderItem
  recall: RecallItem
  score: number                  // Fuse.js score: 0 = perfect, 1 = no match
  confidence: 'HIGH' | 'MEDIUM' | 'LOW'
}

// ─── FLIGHT ────────────────────────────────────────────────────────────────────

export interface FlightData {
  flight_number: string
  airline_iata: string
  departure_airport: string
  arrival_airport: string
  scheduled_departure: string    // ISO datetime
  actual_departure: string | null
  scheduled_arrival: string
  actual_arrival: string | null
  status: 'DELAYED' | 'CANCELLED' | 'ON_TIME' | 'DIVERTED'
  delay_minutes: number
}

export interface EU261EligibilityResult {
  eligible: boolean
  reason: string
  compensation_eur: CompensationTier | 0
  regulation: 'EU261' | 'UK261' | 'NONE'
}

// ─── USER ──────────────────────────────────────────────────────────────────────

export interface User {
  id: string
  stripe_customer_id: string | null
  plan: 'free' | 'pro'
  plan_expires_at: string | null
  created_at: string
}
