/**
 * /terms — Terms of Service
 */

import Link from 'next/link'
import { Plane } from 'lucide-react'

const LAST_UPDATED = '13 April 2026'

export const metadata = {
  title: 'Terms of Service | FlyBack',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#08090a] text-[#f7f8f8]">

      {/* Nav */}
      <header className="border-b border-white/[0.05]" style={{ background: 'rgba(8,9,10,0.9)', backdropFilter: 'blur(20px)' }}>
        <nav className="mx-auto flex max-w-[1200px] items-center justify-between px-6 py-[14px]">
          <Link href="/" className="flex items-center gap-2">
            <div className="flex h-[22px] w-[22px] items-center justify-center rounded-[6px] bg-[#638cff]">
              <Plane className="h-3 w-3 text-white" />
            </div>
            <span className="text-[16px] font-[590] leading-[24px] text-[#f7f8f8]">FlyBack</span>
          </Link>
          <Link href="/check"
            className="rounded-full bg-[#f7f8f8] px-[14px] py-[6px] text-[13px] leading-[19.5px] text-[#08090a] hover:opacity-90">
            Check my flight
          </Link>
        </nav>
      </header>

      <main className="mx-auto max-w-[720px] px-6 py-[88px]">

        <div className="mb-[48px]">
          <p className="text-[13px] leading-[19.5px] text-[#638cff] mb-2">Legal</p>
          <h1 className="text-[40px] font-[590] leading-[1.1] tracking-[-0.025em] text-[#f7f8f8]">
            Terms of Service
          </h1>
          <p className="mt-3 text-[13px] leading-[19.5px] text-[#8a8f98]">Last updated: {LAST_UPDATED}</p>
        </div>

        <div className="space-y-[40px]">

          <Section title="1. Acceptance of terms">
            <p>By creating an account or using FlyBack (&ldquo;Service&rdquo;), you agree to these Terms of Service (&ldquo;Terms&rdquo;). If you do not agree, do not use the Service. These Terms form a binding agreement between you and FlyBack.</p>
          </Section>

          <Section title="2. Description of service">
            <p>FlyBack is a subscription software tool that helps airline passengers:</p>
            <ul>
              <li>Determine whether their flight disruption qualifies for compensation under EU Regulation 261/2004 or UK261.</li>
              <li>Generate claim letters addressed to airlines.</li>
              <li>Generate escalation letters to National Enforcement Bodies (NEBs) or Alternative Dispute Resolution (ADR) bodies.</li>
              <li>Track the status of their claims.</li>
            </ul>
            <p>FlyBack is a <strong>self-service tool</strong>, not a legal representative or claims management company. We do not act as your agent, lawyer, or representative. We do not submit claims on your behalf.</p>
          </Section>

          <Section title="3. Eligibility">
            <p>You must be at least 18 years old to use the Service. By using FlyBack, you represent that you are the passenger named in the flight booking or have authority to act on that passenger&rsquo;s behalf.</p>
          </Section>

          <Section title="4. Subscription and payment">
            <ul>
              <li>FlyBack is available for €10 per month (or equivalent in your billing currency), billed monthly.</li>
              <li>A 14-day free trial is offered to new subscribers. No credit card is required to start.</li>
              <li>Payment is processed by Stripe. Your billing information is subject to Stripe&rsquo;s terms and privacy policy.</li>
              <li>You may cancel your subscription at any time from account settings. Cancellation takes effect at the end of the current billing period; no partial refunds are issued.</li>
              <li>We reserve the right to change pricing with 30 days&rsquo; notice. Existing subscribers will be notified by email before any price change takes effect.</li>
            </ul>
          </Section>

          <Section title="5. No legal advice">
            <p>Nothing on FlyBack constitutes legal advice. The claim letters generated by FlyBack are templates based on publicly available regulatory text. FlyBack makes no guarantee that any claim will be successful. Airline decisions, court judgments, and regulatory outcomes are outside our control.</p>
            <p>For complex disputes or legal proceedings, we recommend consulting a qualified lawyer or accredited claims management company in your jurisdiction.</p>
          </Section>

          <Section title="6. Accuracy of information">
            <p>You are responsible for the accuracy of all information you enter into FlyBack. Submitting false or misleading information in a claim letter may constitute fraud. FlyBack is not liable for any consequences arising from inaccurate information you provide.</p>
          </Section>

          <Section title="7. Acceptable use">
            <p>You agree not to:</p>
            <ul>
              <li>Use FlyBack for any unlawful purpose or to submit fraudulent claims.</li>
              <li>Reverse engineer, scrape, or attempt to extract data from the Service.</li>
              <li>Share your account credentials with others.</li>
              <li>Use automated scripts or bots to interact with the Service.</li>
            </ul>
            <p>We reserve the right to suspend or terminate accounts that violate these rules.</p>
          </Section>

          <Section title="8. Intellectual property">
            <p>All content, software, and design of FlyBack are owned by or licensed to us. You may not reproduce, distribute, or create derivative works without our prior written consent. Claim letters generated for your personal use are yours to use freely.</p>
          </Section>

          <Section title="9. Limitation of liability">
            <p>To the maximum extent permitted by applicable law, FlyBack shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including lost compensation, lost profits, or data loss.</p>
            <p>Our total aggregate liability to you for any claim arising from use of FlyBack shall not exceed the total fees you paid to us in the 12 months preceding the claim.</p>
          </Section>

          <Section title="10. Modifications">
            <p>We may update these Terms from time to time. We will notify you of material changes by email at least 14 days before they take effect. Continued use of the Service after that date constitutes acceptance of the updated Terms.</p>
          </Section>

          <Section title="11. Governing law">
            <p>These Terms are governed by and construed in accordance with the laws of Ireland (EU). Any disputes shall be subject to the exclusive jurisdiction of the courts of Ireland, without prejudice to your rights as a consumer under applicable EU law.</p>
          </Section>

          <Section title="12. Contact">
            <p>For questions about these Terms, email <a href="mailto:legal@flyback.app">legal@flyback.app</a>.</p>
          </Section>

        </div>
      </main>

      <footer className="border-t border-white/[0.05] py-[40px]">
        <div className="mx-auto max-w-[1200px] px-6 flex flex-wrap justify-between gap-4 text-[13px] leading-[19.5px] text-[#8a8f98]">
          <p>© 2026 FlyBack</p>
          <div className="flex gap-6">
            <Link href="/privacy" className="hover:text-[#f7f8f8] transition-colors">Privacy</Link>
            <Link href="/eu261" className="hover:text-[#f7f8f8] transition-colors">EU261</Link>
            <Link href="/uk261" className="hover:text-[#f7f8f8] transition-colors">UK261</Link>
          </div>
        </div>
      </footer>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="mb-4 text-[20px] font-[590] leading-[1.2] tracking-[-0.01em] text-[#f7f8f8]">{title}</h2>
      <div className="space-y-3 text-[15px] leading-[24px] text-[#8a8f98] [&_strong]:text-[#f7f8f8] [&_a]:text-[#638cff] [&_a]:no-underline [&_a:hover]:underline [&_ul]:pl-5 [&_ul]:space-y-2 [&_ul]:list-disc [&_ul]:marker:text-[#8a8f98]">
        {children}
      </div>
    </section>
  )
}
